  services:
  - type: web
    name: popicron
    runtime: node
    plan: free
    autoDeploy: true
    healthCheckPath: /
    buildCommand: ""
    envVars:
      - key: APP_ENV
        value: production
