  services:
  - type: web
    name: popicron
    runtime: node
    plan: free
    autoDeploy: true
    healthCheckPath: /
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000"
    envVars:
      - key: APP_ENV
        value: production
